from enum import Enum

class TipoViaje(Enum):
    NACIONAL = "NACIONAL"
    INTERNACIONAL = "INTERNACIONAL"

class TipoGasto(Enum):
    TRANSPORTE = "TRANSPORTE"
    ALOJAMIENTO = "ALOJAMIENTO"
    ALIMENTACION = "ALIMENTACION"
    ENTRETENIMIENTO = "ENTRETENIMIENTO"
    COMPRAS = "COMPRAS"
    OTROS = "OTROS"

class MedioPago(Enum):
    EFECTIVO = "EFECTIVO"
    TARJETA_CREDITO = "TARJETA CREDITO"
    TARJETA_DEBITO = "TARJETA DEBITO"
